### ISSUE TITLE
load more than 20 repos

### ISSUE THREAD

**Issue by maxandersen** [moollaza/repo-remover#138]
**Describe the bug**
I have 300+ repos and when using repo-remover only ~20 are shown.

**Comment by moollaza** [comment]
@maxandersen thanks for mentiong this. I'd like to add functionality to handled pages API response from GitHub but haven't had the time lately.

That should enable you to see all your repos, instead of the first 100 repos GitHub returns in the first API call.

**Comment by maxandersen** [comment]
cool - I hope you make it work as it would be nice to more easily cleanup github repos.

in meantime for those who are okey running things locally I made this jbang.dev script to help solve my problem: https://gist.github.com/maxandersen/1dac989e2a9cfc55d79cbb3e0d242e22 maybe others can use that too.

**Comment by moollaza** [comment]
This has been implemented.
