### ISSUE TITLE
VUE_APP_FATHOM_SITE_ID bug on `yarn serve`

### ISSUE THREAD

**Issue by yagoazedias** [moollaza/repo-remover#140]
**Describe the bug**
A bug appears on my startup application, `Template execution failed: ReferenceError: VUE_APP_FATHOM_SITE_ID is not defined`

**To Reproduce**
1. Clone the repo onto your machine
2. Install the node version v10.19.0 with nvm
3. Execute with yarn serve

**Expected behavior**
**Screenshots**
You should see something like the image below
<img width="667" alt="Screen Shot 2020-07-27 at 21 05 12" src="https://user-images.githubusercontent.com/11080296/88604016-e073d180-d04c-11ea-9e2d-0cc61c107eb8.png">

**Desktop (please complete the following information):**
 - OS: MacOS - Catalina 10.15.6 (19G73)
 - Version v10.19.0 

**Additional context**
I'll keep trying to execute, if for some reason i find out what is going on I'll close the issue or create a PR 👍

**Comment by moollaza** [comment]
@yagoazedias thanks for posting this.

I guess you'll need to define that ENV variable in order for this to work. I suppose I could put a `.env` file in the repo with a blank value for that. You could do the same or just run `VUE_APP_FATHOM_SITE_ID='' yarn serve`

Alternatively, you could also remove the bit of HTML that references that in `index.html` (at the bottom). It's only used to pass along the Fathom Analytics Site ID to a script tag

**Comment by yboujraf** [comment]
Dear,

I created the .env file and added :

```
VUE_APP_FATHOM_SITE_ID='';
```

and it fixes the issue.

Best Regards

Youssef

**Comment by dkebler** [comment]
or remove that html in /public that worked too.

**Comment by dkebler** [comment]
well that didn't work as when I went to delete the app posted
Failed to delete "logger": fathom is not defined

**Comment by dkebler** [comment]
I take it back.  They were deleted despite the error message.  All an all this Fathom analytics was a distraction.  Is it really necessary?  Maybe you can make it optional and off by default.

**Comment by moollaza** [comment]
@dkebler I've pushed an update. Fathom should be ignored in dev mode.
