### ISSUE TITLE
repo-remover status?

### ISSUE THREAD

**Issue by janosh** [moollaza/repo-remover#168]
I'm getting an infinite spinner on the latest Chrome (85) and macOS (10.15.7). Disabled all Chrome extensions just in case. Problem remains.

![spinner](https://user-images.githubusercontent.com/30958850/95188967-85d5bf00-07cd-11eb-9a9f-994b9c1e6275.png)

**Comment by cleor41** [comment]
Same

**Comment by moollaza** [comment]
I just tested and it seems to be working currently. 

Maybe the GitHub API was having issues yesterday? Or do you have a lot of repos?

Let me know if you're still having trouble.

**Comment by janosh** [comment]
Just retested. Still not working for me. Nothing logged to console.

**Comment by moollaza** [comment]
Thanks for confirming @janosh 

I've confirmed the breakage occurred in this PR: https://github.com/moollaza/repo-remover/pull/156

It should be working in the previous build here: https://repo-remover-git-dependabot-npmandyarndot-prop-421.moollaza.vercel.app/

I'll have to debug what changed in the VueJS update that caused this breakage.

**Comment by moollaza** [comment]
This should be fixed. I've reverted the PR that caused the issue.

I dug into this for a while, but can't determine what's actually causing the issue.

It appears that for some reason the `result()` callback is not called in Chrome/Safari when the GraphQl API response is returned, so the loading state is never disabled.

**Comment by janosh** [comment]
Confirmed working again. Thanks a lot!
