### ISSUE TITLE
Not showing repos owned by my organisation

### ISSUE THREAD

**Issue by kenpower** [moollaza/repo-remover#171]
**Describe the bug**
Not showing repos owned by my organisation

**To Reproduce**
Enter PAT and only see repos I have created

**Expected behavior**
I expect to see repos own by my organisation that were created by others

I tried adding org scope to token, but did not work

**Comment by moollaza** [comment]
@kenpower did you include the scopes for organization access? 

If you have that, and you have access to org repos, you should be able to see and modify them. I just generated a new token and confirmed I was able to see org repos that I did not create

Example:
![Admin Org Scope](https://user-images.githubusercontent.com/873785/140770327-f7b3a3d9-a745-4d78-8b3f-f8fd7a51c59e.png)
.

**Comment by kenpower** [comment]
Thanks @moollaza I tried it last week with org scope and it didn't work then. 

But I tried it again just now and it works <confused>! So thanks!
