### ISSUE TITLE
Allow organization repos to be displayed/managed

### ISSUE THREAD

**Issue by akamen** [moollaza/repo-remover#20]
**Is your feature request related to a problem? Please describe.**
Personal repos show up just great, would be awesome to see organization related repos.

**Describe the solution you'd like**
Allow for the UI to toggle between user and organization

**Describe alternatives you've considered**

**Additional context**

**Comment by nakednous** [comment]
any news on this one?

**Comment by moollaza** [comment]
@nakednous unfortunately I've been busy lately. I started looking into it a while back but was having difficulty getting this working. 

If anyone familiar with organizations and the v4 API it could help I'd appreciate it.

**Comment by moollaza** [comment]
Hey everyone! I've just pushed live an update that adds support for Organization repos. Please let me know if you have any more feedback!
