### ISSUE TITLE
Not seeing github icon on home page

### ISSUE THREAD

**Issue by akanshgulati** [moollaza/repo-remover#3]
**Describe the bug**
Not able to see the Github icon on the button at Home page.

**To Reproduce**
1. Go to Home page

**Expected behavior**
An Icon should come instead of square block.

**Screenshots**
<img width="379" alt="Screen Shot 2019-03-26 at 3 09 41 PM" src="https://user-images.githubusercontent.com/5287100/54986859-6f945380-4fd9-11e9-9fcb-f784fd8db56e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome Canary
 - Version 75.0.3739.0

**Comment by moollaza** [comment]
Fixed 👍
