### ISSUE TITLE
When inserting personal token on the apposite form loops on validating

### ISSUE THREAD

**Issue by salvob41** [moollaza/repo-remover#76]
**Describe the bug**
If you insert a token (right or wrong doesn't matter), it keeps trying to validate and could not get past through it

**To Reproduce**
1. Go to the homepage
2. Paste a token into the input

**Expected behavior**
Token should validate instantly

**Screenshots**
![image](https://user-images.githubusercontent.com/6097015/71987863-40c93000-322f-11ea-8565-bd00ab4fbc12.png)

**Desktop (please complete the following information):**
 - OS: ?
 - Browser: Chrome
 - Version: ?

**Additional context**
In the Developers toolkit of Chrome's browser it gives this maybe related error:
![image](https://user-images.githubusercontent.com/6097015/71987966-681ffd00-322f-11ea-87b4-cbbf0a5d36db.png)

**Comment by moollaza** [comment]
@salvob41 thanks for reporting. This seems to be affecting Chrome and Safari. However Firefox and Brave appear to be OK currently. I recently updated some dependencies and I suspect its related to the Apollo update...

**Comment by moollaza** [comment]
@salvob41 it seems like this was caused by #60. I've reverted and re-deployed. It is now working for me in Chrome. Can you please confirm it's fixed for you as well?

**Comment by salvob41** [comment]
that was extremely efficient :D 
I can confirm it works now :) thank you @moollaza 
We can close it now
